EdifyPractice/Controllers/BackendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace EdifyPractice.Controllers
{
    public class BackendController : Controller
    {
        public IActionResult SchoolWizardForm()
        {
            return View("~/Views/Backend/SuperAdmin/SchoolWizardForm.cshtml");
        }

        public IActionResult SchoolsList()
        {
            return View("~/Views/Backend/SuperAdmin/SchoolsList.cshtml");
        }

        public IActionResult CreateNewBranch()
        {
            return View("~/Views/Backend/SuperAdmin/CreateNewBranch.cshtml");
        }

        public IActionResult CreateSchoolAdmin()
        {
            return View("~/Views/Backend/SuperAdmin/CreateSchoolAdmin.cshtml");
        }
}
}

EdifyPractice/Views/Backend/SuperAdmin/CreateNewBranch.cshtml
@{
    ViewData["Title"] = "CreateNewBranch";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<div class="ks-page-header">
    <section class="ks-title">
        <h3>Add New Branch</h3>
    </section>
</div>

<div class="ks-page-content">
    <div class="ks-page-content-body">
        <div class="card">
            <div class="card-block">
                <h5 class="card-title">Branch Details:-</h5>
                <div class="row">

                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">Select School</label>
                            <select class="form-control">
                                <option>Select School</option>
                                <option>Allied School</option>
                                <option>Lahore Grammar School</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">Branch Name</label>
                            <input type="text" id="branch-name" class="form-control school-address" maxlength="9">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">Branch Address</label>
                            <input type="text" id="branch-address" class="form-control school-address" maxlength="9">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">Branch Phone No</label>
                            <input type="text" id="branch-phone-no" class="form-control school-phone-no" maxlength="9">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">Branch Email</label>
                            <input type="text" id="branch-email" class="form-control school-email" maxlength="9">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="form-group">
                            <button id="btn-create-branch" class="btn btn-primary">Create Branch</button>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

EdifyPractice/Views/Backend/SuperAdmin/CreateSchoolAdmin.cshtml
@{
    ViewData["Title"] = "CreateSchoolAdmin";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<div class="ks-page-header">
    <section class="ks-title">
        <h3>Add New School Admin</h3>
    </section>
</div>
<div class="ks-page-content">
    <div class="ks-page-content-body">
        <div class="card">
            <div class="card-block">
                <h5 class="card-title">School Admin Details:-</h5>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">Select School</label>
                            <select class="form-control">
                                <option>Select School</option>
                                <option>Allied School</option>
                                <option>Lahore Grammar School</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">Select Branch</label>
                            <select class="form-control">
                                <option>Select Branch</option>
                                <option>Branch A</option>
                                <option>Branch B</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">School Admin Name</label>
                            <input type="text" id="branch-name" class="form-control school-address" maxlength="9">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">School Admin Email</label>
                            <input type="text" id="branch-address" class="form-control school-address" maxlength="9">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">School Admin Username</label>
                            <input type="text" id="branch-phone-no" class="form-control school-phone-no" maxlength="9">
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="ks-phone-mask-input">School Admin Password</label>
                            <input type="text" id="branch-email" class="form-control school-email" maxlength="9">
                        </div>
                    </div>
                    
                    <div class="col-lg-4">
                        <div class="form-group">
                            <button id="btn-create-branch" class="btn btn-primary">Create School Admin</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

EdifyPractice/Views/Backend/SuperAdmin/SchoolWizardForm.cshtml
@{
    ViewData["Title"] = "SchoolWizardForm";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}


<div class="ks-page-header">
    <section class="ks-title">
        <h3>Add New School</h3>
    </section>
</div>


<div class="ks-page-content">
    <div class="ks-page-content-body ks-tabs-page-container">
        <div class="ks-tabs-container-description">
            <h3>School Creation Steps</h3>               
        </div>
        <ul class="nav ks-nav-tabs ks-tabs-page-default ks-tabs-full-page">
            <li class="nav-item">
                <a class="nav-link active show" href="#" data-toggle="tab" data-target="#new-school">
                    Create New School
                    
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="tab" data-target="#new-branch">
                    Create A Branch
                    
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="tab" data-target="#school-admin">
                    Create School Admin
                    
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active show" id="new-school" role="tabpanel">
                <div class="card">
                    <div class="card-block">
                        <h5 class="card-title">School Details:-</h5>
                        <div class="row">
                            
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">School Name</label>
                                    <input type="text" id="school-name" class="form-control school-name" maxlength="9">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">School Address</label>
                                    <input type="text" id="school-address" class="form-control school-address" maxlength="9">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">School Phone No</label>
                                    <input type="text" id="school-phone-no" class="form-control school-phone-no" maxlength="9">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">School Email</label>
                                    <input type="text" id="school-email" class="form-control school-email" maxlength="9">
                                </div>
                            </div>

                            <div class="col-lg-4">
                                <div class="form-group">
                                    <button id="btn-create-school" class="btn btn-primary">Create School</button>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
            <div class="tab-pane" id="new-branch" role="tabpanel">
                <div class="card">
                    <div class="card-block">
                        <h5 class="card-title">Branch Details:-</h5>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="select-school-for-branch">School</label>
                                    <select id="select-school-for-branch" class="form-control">
                                        <option>Select a School</option>
                                        <option>Select</option>
                                        <option>Select</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">Branch Name</label>
                                    <input type="text" id="branch-name" class="form-control branch-name" maxlength="9">
                                </div>
                            </div>                                                                                    
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">Branch Address</label>
                                    <input type="text" id="branch-address" class="form-control branch-address" maxlength="9">
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">Branch Phone No</label>
                                    <input type="text" id="branch-phone-no" class="form-control branch-phone-no" maxlength="9">
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">Branch Email</label>
                                    <input type="text" id="branch-email" class="form-control branch-email" maxlength="9">
                                </div>
                            </div>
                             
                            <div class="col-lg-4">
                                <div class="form-group">                                    
                                    <button id="btn-create-branch" class="btn btn-primary">Create Branch</button>
                                </div>
                            </div>  
                        </div>


                    </div>
                </div>
            </div>
            <div class="tab-pane" id="school-admin" role="tabpanel">
                <div class="card">
                    <div class="card-block">
                        <h5 class="card-title">School Admin Details:-</h5>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">Name</label>
                                    <input type="text" id="school-admin-name" class="form-control school-admin-name" maxlength="9">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">Email</label>
                                    <input type="text" id="school-admin-email" class="form-control school-admin-email" maxlength="9">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">Username</label>
                                    <input type="text" id="school-admin-username" class="form-control school-admin-username" maxlength="9">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="ks-phone-mask-input">Password</label>
                                    <input type="text" id="school-admin-password" class="form-control school-admin-password" maxlength="9">
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <button id="btn-add-school-admin" class="btn btn-primary">Add School Admin</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>



@section Scripts {
    
    
    

   
}

EdifyPractice/Views/Backend/SuperAdmin/SchoolsList.cshtml
@{
    ViewData["Title"] = "SchoolsList";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<div class="ks-page-header">
    <section class="ks-title">
        <h3>Schools List</h3>
    </section>
</div>


<div class="ks-page-content">
    <div class="ks-page-content-body">
        <div class="container-fluid ks-rows-section">
            <div class="row">
                <div class="col-lg-12 ks-panels-column-section">
                    <div class="card panel ks-information ks-light">
                        <h5 class="card-header">
                            <span class="ks-text">Schools</span>
                            <a asp-controller="Backend" asp-action="SchoolWizardForm" class="btn btn-outline-primary ks-light">Add New School</a>
                        </h5>
                        <div class="card-block ks-datatable">
                            <div id="ks-sales-datatable_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer" style="width: 1226px;">
                                <table id="ks-sales-datatable" class="table table-bordered dataTable no-footer" style="width: 100%;" width="100%" role="grid" aria-describedby="ks-sales-datatable_info">
                                    <thead>
                                    <tr role="row"><th class="sorting_asc" tabindex="0" aria-controls="ks-sales-datatable" rowspan="1" colspan="1" aria-label="Reference: activate to sort column descending" style="width: 203px;" aria-sort="ascending">School Id</th><th class="sorting" tabindex="0" aria-controls="ks-sales-datatable" rowspan="1" colspan="1" aria-label="Date: activate to sort column ascending" style="width: 195px;">School Name</th><th class="sorting" tabindex="0" aria-controls="ks-sales-datatable" rowspan="1" colspan="1" aria-label="Assigned To: activate to sort column ascending" style="width: 237px;">Address</th><th class="sorting" tabindex="0" aria-controls="ks-sales-datatable" rowspan="1" colspan="1" aria-label="Status: activate to sort column ascending" style="width: 307px;">Phone No</th><th class="sorting" tabindex="0" aria-controls="ks-sales-datatable" rowspan="1" colspan="1" aria-label="&amp;nbsp;: activate to sort column ascending" style="width: 24px;">&nbsp;</th></tr>
                                    </thead>
                                    <tbody>

                                    <tr role="row" class="odd">
                                        <td class="sorting_1">
                                            <a href="#">E00673</a>
                                        </td>
                                        <td>14 Sep, 2016</td>
                                        <td>
                                            <div class="ks-user">
                                                <img class="ks-avatar" src="assets/img/avatars/ava-3.png" width="24" height="24">
                                                <span class="ks-name">Ian Potter</span>
                                            </div>
                                        </td>
                                        <td>
                                            <span class="badge ks-circle badge-info">Quotes in progress</span>
                                        </td>
                                        <td class="ks-controls">
                                            <div class="dropdown">
                                                <a class="btn btn-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <span class="la la-ellipsis-h"></span>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1" x-placement="top-end" style="position: absolute; transform: translate3d(24px, -8px, 0px); top: 0px; left: 0px; will-change: transform;">
                                                    <a class="dropdown-item" href="#">Action</a>
                                                    <a class="dropdown-item" href="#">Another action</a>
                                                    <a class="dropdown-item" href="#">Something else here</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr role="row" class="even">
                                        <td class="sorting_1">
                                            <a href="#">E00673</a>
                                        </td>
                                        <td>14 Sep, 2016</td>
                                        <td>
                                            <div class="ks-user">
                                                <img class="ks-avatar" src="assets/img/avatars/ava-2.png" width="24" height="24">
                                                <span class="ks-name">Brent Dean</span>
                                            </div>
                                        </td>
                                        <td><span class="badge ks-circle badge-warning">New</span></td>
                                        <td class="ks-controls">
                                            <div class="dropdown">
                                                <a class="btn btn-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <span class="la la-ellipsis-h"></span>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                                                    <a class="dropdown-item" href="#">Action</a>
                                                    <a class="dropdown-item" href="#">Another action</a>
                                                    <a class="dropdown-item" href="#">Something else here</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr role="row" class="odd">
                                        <td class="sorting_1">
                                            <a href="#">E00673</a>
                                        </td>
                                        <td>14 Sep, 2016</td>
                                        <td>
                                            <div class="ks-user">
                                                <img class="ks-avatar" src="assets/img/avatars/ava-4.png" width="24" height="24">
                                                <span class="ks-name">Brent Dean</span>
                                            </div>
                                        </td>
                                        <td><span class="badge ks-circle badge-danger">Error</span></td>
                                        <td class="ks-controls">
                                            <div class="dropdown">
                                                <a class="btn btn-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <span class="la la-ellipsis-h"></span>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                                                    <a class="dropdown-item" href="#">Action</a>
                                                    <a class="dropdown-item" href="#">Another action</a>
                                                    <a class="dropdown-item" href="#">Something else here</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr role="row" class="even">
                                        <td class="sorting_1">
                                            <a href="#">E00673</a>
                                        </td>
                                        <td>14 Sep, 2016</td>
                                        <td>
                                            <div class="ks-user">
                                                <img class="ks-avatar" src="assets/img/avatars/ava-1.png" width="24" height="24">
                                                <span class="ks-name">Brent Dean</span>
                                            </div>
                                        </td>
                                        <td><span class="badge ks-circle badge-success">Completed</span></td>
                                        <td class="ks-controls">
                                            <div class="dropdown">
                                                <a class="btn btn-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <span class="la la-ellipsis-h"></span>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                                                    <a class="dropdown-item" href="#">Action</a>
                                                    <a class="dropdown-item" href="#">Another action</a>
                                                    <a class="dropdown-item" href="#">Something else here</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table><div class="dataTables_info" id="ks-sales-datatable_info" role="status" aria-live="polite">Showing 1 to 4 of 18 entries</div><div class="dataTables_paginate paging_simple_numbers" id="ks-sales-datatable_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="ks-sales-datatable_previous"><a href="#" aria-controls="ks-sales-datatable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="ks-sales-datatable" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="ks-sales-datatable" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="ks-sales-datatable" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="ks-sales-datatable" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="ks-sales-datatable" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item next" id="ks-sales-datatable_next"><a href="#" aria-controls="ks-sales-datatable" data-dt-idx="6" tabindex="0" class="page-link">Next</a></li></ul></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts
{
    <script src="~/assets/backend/plugins/datatables-net/media/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/backend/plugins/datatables-net/media/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/assets/backend/plugins/swiper/js/swiper.jquery.min.js"></script>
    
    
<script type="application/javascript">
        $(document).ready(function() {
            var salesDataTable = $('#ks-sales-datatable').DataTable({
                dom: 'rtip',
                pageLength: 10
            });
            $('.dataTables_wrapper').css('width', $('.dataTables_wrapper').closest('.panel').width() + 10);
            salesDataTable.columns.adjust().draw();

            $('.swiper-container').width($('.swiper-container').closest('.ks-slider').width());

            var swiper = new Swiper ('.swiper-container', {
                paginationClickable: true,
                slidesPerView: 5,
                spaceBetween: 20,
                pagination: '.swiper-pagination',
                breakpoints: {
                    1024: {
                        slidesPerView: 5,
                        spaceBetween: 40
                    },
                    768: {
                        slidesPerView: 3,
                        spaceBetween: 30
                    },
                    640: {
                        slidesPerView: 2,
                        spaceBetween: 20
                    },
                    320: {
                        slidesPerView: 1,
                        spaceBetween: 10
                    }
                }

                /*// Navigation arrows
                 nextButton: '.swiper-button-next',
                 prevButton: '.swiper-button-prev'*/
            })
        });
</script>
}